from enum import Enum

class RobotRedisElement:
    ROBOT_AUTHENTICATION        = "hello" # FIXME

    ROBOT_POSITION              = "NAV_GLOBAL_POSITION"
    ROBOT_SPEED                 = "NAV_CURR_SPEED"
    ROBOT_ROUTE_ID              = "NAV_ROAD_CURRENT_ID"
    NAV_BATTERY_VOLTAGE         = "NAV_BATTERY_VOLTAGE"
    NAV_BATTERY_PERCENTAGE      = "NAV_BATTERY_PERCENTAGE"

    HARD_TEMPERATURE_RC_INFO    = "HARD_TEMPERATURE_INFO"

    HARD_MCU_MOTOR_COM_STATE    = "HARD_MCU_MOTOR_COM_STATE"
    HARD_MCU_CARGO_COM_STATE    = "HARD_MCU_CARGO_COM_STATE"
    HARD_MCU_INTER_COM_STATE    = "HARD_MCU_INTER_COM_STATE"
    HARD_PIXHAWK_COM_STATE      = "HARD_PIXHAWK_COM_STATE"
    HARD_LOCAL_JS_COM_STATE     = "HARD_LOCAL_JS_COM_STATE"